# Child Application for the py-api tenant (Python/FastAPI) .
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: py-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Linkify-Solutions-Inc/kubernetes-vercel.git
    targetRevision: main
    path: gitops/manifests/py-api
  destination:
    server: https://kubernetes.default.svc
    namespace: app-py-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
